"""Group output port — repository Protocol (driven side of hexagon)."""

from typing import Any, Protocol

from src.domain.group.entities import Group


class IGroupRepository(Protocol):
    def create(self, group: Group) -> Group: ...
    def get_all(self) -> list[Group]: ...
    def get_by_id(self, group_id: int) -> Group: ...
    def get_by_link_url(self, link_url: str) -> Group: ...
    def update(self, group_id: int, **fields: Any) -> Group: ...
    def delete(self, group_id: int) -> None: ...
