"""adds upgraded at

Revision ID: 34a8d5299c7e
Revises: 821767a0b48d
Create Date: 2024-12-05 21:56:42.188183

"""

# revision identifiers, used by Alembic.
revision = "34a8d5299c7e"
down_revision = "821767a0b48d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
