"""create_symphony_tables

Revision ID: 41a0fefb2dc6
Revises: 42b1beebae2e
Create Date: 2026-05-06 11:06:34.739310

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41a0fefb2dc6"
down_revision = "42b1beebae2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "symphony_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issue_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("workspace_path", sa.String(length=1024), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_symphony_runs_issue_id"), "symphony_runs", ["issue_id"], unique=False
    )
    op.create_index(
        op.f("ix_symphony_runs_next_attempt_at"),
        "symphony_runs",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_symphony_runs_status"), "symphony_runs", ["status"], unique=False
    )
    op.create_table(
        "symphony_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["symphony_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "version", name="uq_symphony_plans_run_version"),
    )
    op.create_index(
        op.f("ix_symphony_plans_run_id"), "symphony_plans", ["run_id"], unique=False
    )
    op.create_table(
        "symphony_specs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["symphony_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "version", name="uq_symphony_specs_run_version"),
    )
    op.create_index(
        op.f("ix_symphony_specs_run_id"), "symphony_specs", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_symphony_specs_run_id"), table_name="symphony_specs")
    op.drop_table("symphony_specs")
    op.drop_index(op.f("ix_symphony_plans_run_id"), table_name="symphony_plans")
    op.drop_table("symphony_plans")
    op.drop_index(op.f("ix_symphony_runs_status"), table_name="symphony_runs")
    op.drop_index(op.f("ix_symphony_runs_next_attempt_at"), table_name="symphony_runs")
    op.drop_index(op.f("ix_symphony_runs_issue_id"), table_name="symphony_runs")
    op.drop_table("symphony_runs")
    # ### end Alembic commands ###
