"""Initial migration

Revision ID: 821767a0b48d
Revises:
Create Date: 2024-12-05 21:55:50.905553

"""

# revision identifiers, used by Alembic.
revision = "821767a0b48d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
