"""adds upgraded at

Revision ID: 898fc8180451
Revises: 34a8d5299c7e
Create Date: 2024-12-05 21:57:44.277541

"""

# revision identifiers, used by Alembic.
revision = "898fc8180451"
down_revision = "34a8d5299c7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
