"""removes password column

Revision ID: 9962a7310e25
Revises: 7d26527b923e
Create Date: 2024-12-05 23:54:58.323328

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9962a7310e25"
down_revision = "7d26527b923e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participants", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participants",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
