"""update statusenum

Revision ID: ae6617610d2a
Revises: 9962a7310e25
Create Date: 2024-12-06 00:08:26.030875

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae6617610d2a"
down_revision = "9962a7310e25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
