"""adds upgraded at

Revision ID: cf4bbc3325c5
Revises: 898fc8180451
Create Date: 2024-12-05 22:00:52.738737

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf4bbc3325c5"
down_revision = "898fc8180451"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("link_url", sa.String(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "santa",
                "chocolate",
                "frenemy",
                "book",
                "wine",
                "easter",
                name="categoryenum",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("gift_hint", sa.String(), nullable=True),
        sa.Column(
            "status", sa.Enum("PENDING", "REVEALED", name="statusenum"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_participants_id"), "participants", ["id"], unique=False)
    op.create_table(
        "secret_friends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("gift_giver_id", sa.Integer(), nullable=False),
        sa.Column("gift_receiver_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gift_giver_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gift_receiver_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_secret_friends_id"), "secret_friends", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_secret_friends_id"), table_name="secret_friends")
    op.drop_table("secret_friends")
    op.drop_index(op.f("ix_participants_id"), table_name="participants")
    op.drop_table("participants")
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
