services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: app
  #   restart: always
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL:?Missing DATABASE_URL environment variable}
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Missing POSTGRES_USER environment variable}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Missing POSTGRES_PASSWORD environment variable}
      POSTGRES_DB: ${POSTGRES_DB:?Missing POSTGRES_DB environment variable}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?Missing PGADMIN_DEFAULT_EMAIL environment variable}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?Missing PGADMIN_DEFAULT_PASSWORD environment variable}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
